-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."recipe_ingredients" add column "index" integer
--  not null default '0';
